  

version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Etools/Etools.WebApi.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release --self-contained false -r linux-x64 -o ./build_output Etools/Etools.WebApi.csproj
      - mv appspec.yml ./build_ouput
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
