version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Etools/Etools.WebApi.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release  ./build_output Etools/Etools.WebApi.csproj  --self-contained false
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
